# Generated by Django 4.0.5 on 2022-07-05 16:37

import backend.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('blog', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('artist', models.CharField(max_length=255)),
                ('art', models.ImageField(upload_to=backend.models.upload_path)),
            ],
        ),
    ]
