# Generated by Django 4.0.5 on 2022-06-14 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blog', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('art_Piece', models.ImageField(upload_to='')),
            ],
        ),
    ]
