# Generated by Django 4.0.5 on 2022-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='art_Piece',
            field=models.ImageField(upload_to='files/covers'),
        ),
    ]
